services:
  odoo:
    image: odoo:17.0
    depends_on:
      - db
      - traefik
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-web:/var/lib/odoo
      # - ./config:/etc/odoo  # Optional: custom config directory
      # - ./addons:/mnt/extra-addons  # Optional: custom addons directory
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.odoo-http.entrypoints=http
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.odoo-http.middlewares=redirect-to-https
      - traefik.http.routers.odoo-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.odoo-https.entrypoints=https
      - traefik.http.routers.odoo-https.tls=true
      - traefik.http.services.odoo.loadbalancer.server.port=8069
      - traefik.docker.network=web
    networks:
      - web

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-db:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik
    command:
      - --api.insecure=false  # Set to true for testing, remove in production
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # - --log.level=DEBUG
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.email=${EMAIL}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web    

volumes:
  odoo-web:
  odoo-db:

networks:
  web:
    driver: bridge
