services:
  odoo:
    image: odoo:17.0
    depends_on:
      - db
      - traefik
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
      - ADMIN_PASSWORD=${ODOO_ADMIN_PASS}
    volumes:
      - odoo-web-data:/var/lib/odoo
      # - ./config:/etc/odoo  # Optional: custom config directory
      # - ./addons:/mnt/extra-addons  # Optional: custom addons directory
    labels:
      - traefik.enable=true
      - traefik.https.routers.odoo.rule=Host(`${DOMAIN}`)
      - traefik.https.services.odoo.loadbalancer.server.port=8069
      - traefik.tls.stores.default.defaultgeneratedcert.resolver=myresolver
      - traefik.tls.stores.default.defaultgeneratedcert.domain.main=${DOMAIN}
      - traefik.docker.network=web
    networks:
      - web

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik
    command:
      - --api.insecure=false  # False for production, remove this line to enable it for local testing
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --log.level=DEBUG
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email=postmaster@example.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=https
      - --certificatesresolvers.myresolver.acme.email=${EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true=label
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web    

volumes:
  odoo-web-data:
  odoo-db-data:
  letsencrypt:

networks:
  web:
    driver: bridge
